### ISSUE TITLE
 ERROR  Watcher took too long to load

### ISSUE THREAD

**Issue by wanghaisheng** [ColinEberhardt/ReactNative-PropertyFinder#5]
edwin@192.168.0.112:/Users/edwin/Documents/workfolder/workspace/ReactNative-PropertyFinder  git:(master*) $ npm start

> PropertyFinder@0.0.1 start /Users/edwin/Documents/workfolder/workspace/ReactNative-PropertyFinder
> node_modules/react-native/packager/packager.sh

 ===============================================================
 |  Running packager on port 8081.  
 |  Keep this packager running while developing on any JS  
 |  projects. Feel free to close this tab and run your own  
 |  packager instance if you prefer.  
 |  
 |     https://github.com/facebook/react-native  
 |  
 ===============================================================

Looking for JS files in
   /Users/edwin/Documents/workfolder/workspace/ReactNative-PropertyFinder 

React packager ready.

[23:48:35] <START> fs crawl
[23:48:36] <END>   fs crawl (1376ms)
 ERROR  Watcher took too long to load
Try running `watchman version` from your terminal
https://facebook.github.io/watchman/docs/troubleshooting.html
Error: Watcher took too long to load
Try running `watchman version` from your terminal
https://facebook.github.io/watchman/docs/troubleshooting.html
    at [object Object]._onTimeout (/Users/edwin/Documents/workfolder/workspace/ReactNative-PropertyFinder/node_modules/react-native/packager/react-packager/src/FileWatcher/index.js:98:16)
    at Timer.listOnTimeout (timers.js:89:15)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.

npm ERR! Darwin 14.4.0
npm ERR! argv "/Users/edwin/.nvm/versions/io.js/v2.3.4/bin/iojs" "/Users/edwin/.nvm/versions/io.js/v2.3.4/bin/npm" "start"
npm ERR! node v2.3.4
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE
npm ERR! PropertyFinder@0.0.1 start: `node_modules/react-native/packager/packager.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the PropertyFinder@0.0.1 start script 'node_modules/react-native/packager/packager.sh'.
npm ERR! This is most likely a problem with the PropertyFinder package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/react-native/packager/packager.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls PropertyFinder
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/edwin/Documents/workfolder/workspace/ReactNative-PropertyFinder/npm-debug.log

**Comment by wanghaisheng** [comment]
nvm use iojs
Now using io.js v2.3.4 (npm v2.12.1)
